### ISSUE TITLE
Security - Hardening

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/scd_epics#21]
* AWS, System, and Network hardening
 * Spike: solution for managing credentials and SSH keys (maybe eliminating them)
 * K8s (M)
 * Managed Services (M)
 * AWS platform (Cloudwatch/ GuardDuty) (L)

T-Shirt estimate was made on 05/31/19.
 * S: < 1 pair / .5 sprint
 * M:  1 pair / 1 sprint
 * L: 2 pairs / 1 sprint
 * XL: way >

#### K8 (First Priority)
- SPIKE: Better key management and a way to roll keys (1) 
- SPIKE: Can we put the K8 control plane inside of the VPN? (1)
- SPIKE: Kube Bench - is it worth running a scan? (1)
- SPIKE: Can we have a K8 audit trail of what happened and who did it? (1)
##### Play after AWS Spikes
- SPIKE: How can we access K8 with our own credentials and trace them? (3)
- SPIKE: RBAC for apps/operators - what is the cost/granularity? (3)
- SPIKE: JSR around internal network restrictions i.e. Calico (4)

#### AWS (Second Priority)
- GuardDuty to determine where we are out of compliance (AWS) - currently running, but monitoring isn't in  place.  (2)
- AWS audit/AWS config - should be covered by our credits - needs to be run and then the issues reviewed with the team for prioritization (2)
- SCCIDE needs to be sunset after SMTP is migrated over to ALM/managed service (2)

#### Managed Services (Third Priority)
- SPIKE: Security groups and the networks around our RDS' (5)  (write card for me)
- SPIKE: Audit S3 permissions and privacy - Ram/dev pair (5) . (write card for me)
- Automated updates for elasticache (5) .  (write card for me)
- SPIKE: Review backup policy for compliance and intelligent retention (5)  (punt)
- SPIKE: Can we automatically roll IAM credentials? (5) .  (write card for me)

**Comment by warnerAWESOMEmoore** [comment]
@JarredOlson a lot of the system level hardening findings from AWSInspector were originally intended to be in scope of this epic.
